repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        exclude: node_modules/
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '\.docx$|\.xlsx$|\.png$|\.jpg$'
      - id: trailing-whitespace
        exclude: '\.docx$|\.xlsx$|\.png$|\.md$'
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=500']

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '\.docx$|\.xlsx$|\.png$|node_modules/'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: ['--select', 'E,F,W', '--ignore', 'E501', '--fix']
        files: '\.py$'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ['--severity=error']
        files: '\.sh$'
