#!/usr/bin/env python3
"""Generate NemoClaw PowerSpec Prototype Project Report (.docx)"""

import os
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml

BLUE = RGBColor(0x1F, 0x4E, 0x79)
RED_ORANGE = RGBColor(0xCC, 0x44, 0x00)
GREEN = RGBColor(0x00, 0x80, 0x00)
GRAY = RGBColor(0x66, 0x66, 0x66)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
DARK = RGBColor(0x33, 0x33, 0x33)
LIGHT_BLUE_BG = "D6E4F0"
HEADER_BG = "1F4E79"

doc = Document()

# -- Style setup --
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(10.5)
style.font.color.rgb = DARK
style.paragraph_format.space_after = Pt(4)

for level in range(1, 4):
    hs = doc.styles[f'Heading {level}']
    hs.font.color.rgb = BLUE
    hs.font.name = 'Calibri'
    if level == 1:
        hs.font.size = Pt(18)
        hs.font.bold = True
    elif level == 2:
        hs.font.size = Pt(14)
        hs.font.bold = True
    else:
        hs.font.size = Pt(12)
        hs.font.bold = True

# -- Helpers --
def set_cell_shading(cell, color_hex):
    shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>')
    cell._tc.get_or_add_tcPr().append(shading)

def add_table(doc, headers, rows, col_widths=None):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    # Header row
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = ''
        p = cell.paragraphs[0]
        run = p.add_run(h)
        run.bold = True
        run.font.color.rgb = WHITE
        run.font.size = Pt(9.5)
        run.font.name = 'Calibri'
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        set_cell_shading(cell, HEADER_BG)
    # Data rows
    for r_idx, row_data in enumerate(rows):
        for c_idx, val in enumerate(row_data):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = ''
            p = cell.paragraphs[0]
            run = p.add_run(str(val))
            run.font.size = Pt(9)
            run.font.name = 'Calibri'
            if r_idx % 2 == 1:
                set_cell_shading(cell, "F2F2F2")
    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = Cm(w)
    return table

def add_para(text, style_name='Normal', bold=False, size=None, color=None, align=None, space_after=None):
    p = doc.add_paragraph(style=style_name)
    run = p.add_run(text)
    if bold:
        run.bold = True
    if size:
        run.font.size = size
    if color:
        run.font.color.rgb = color
    if align:
        p.alignment = align
    if space_after is not None:
        p.paragraph_format.space_after = space_after
    return p

def add_bullet(text, bold_prefix=None):
    p = doc.add_paragraph(style='List Bullet')
    if bold_prefix:
        r = p.add_run(bold_prefix)
        r.bold = True
        r.font.size = Pt(10.5)
        r.font.name = 'Calibri'
        r2 = p.add_run(text)
        r2.font.size = Pt(10.5)
        r2.font.name = 'Calibri'
    else:
        r = p.add_run(text)
        r.font.size = Pt(10.5)
        r.font.name = 'Calibri'
    return p

def add_issue(num, title, severity, date, problem, root_cause, fix, status):
    p = doc.add_paragraph()
    r = p.add_run(f"Issue {num}: {title} ({severity} — {date})")
    r.bold = True
    r.font.size = Pt(11)
    r.font.color.rgb = BLUE
    r.font.name = 'Calibri'
    for label, val in [("Problem:", problem), ("Root Cause:", root_cause), ("Fix:", fix), ("Status:", status)]:
        bp = doc.add_paragraph(style='List Bullet')
        rl = bp.add_run(f"{label} ")
        rl.bold = True
        rl.font.size = Pt(10)
        rl.font.name = 'Calibri'
        rv = bp.add_run(val)
        rv.font.size = Pt(10)
        rv.font.name = 'Calibri'

# -- Footer --
section = doc.sections[0]
section.top_margin = Cm(2.5)
section.bottom_margin = Cm(2.5)
section.left_margin = Cm(2.5)
section.right_margin = Cm(2.5)

footer = section.footer
footer.is_linked_to_previous = False
fp = footer.paragraphs[0]
fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
fr = fp.add_run("Project NemoClaw PowerSpec Prototype | Confidential | Generated by Jarvis AI | April 13, 2026")
fr.font.size = Pt(8)
fr.font.color.rgb = GRAY
fr.font.name = 'Calibri'
# Page number
fp.add_run("    |    Page ")
fld_xml = (
    '<w:fldSimple {} w:instr=" PAGE "><w:r><w:t>1</w:t></w:r></w:fldSimple>'
).format(nsdecls('w'))
fp._p.append(parse_xml(fld_xml))

# ===== TITLE PAGE =====
for _ in range(6):
    doc.add_paragraph()

add_para("Project NemoClaw PowerSpec Prototype", bold=True, size=Pt(28), color=BLUE, align=WD_ALIGN_PARAGRAPH.CENTER)
add_para("Project Report", bold=True, size=Pt(20), color=BLUE, align=WD_ALIGN_PARAGRAPH.CENTER, space_after=Pt(24))
add_para("Jarvis AI Infrastructure  |  April 12–13, 2026", size=Pt(14), color=GRAY, align=WD_ALIGN_PARAGRAPH.CENTER, space_after=Pt(36))

# Status badge
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run("STATUS: Phase 0 Pending — Awaiting Eric Manual Setup")
r.bold = True
r.font.size = Pt(14)
r.font.color.rgb = RED_ORANGE
r.font.name = 'Calibri'

for _ in range(4):
    doc.add_paragraph()

add_para("Prepared by: Jarvis AI Assistant", size=Pt(11), color=GRAY, align=WD_ALIGN_PARAGRAPH.CENTER)
add_para("For: Eric Brown — CFO & COO, Cohesity", size=Pt(11), color=GRAY, align=WD_ALIGN_PARAGRAPH.CENTER)
add_para("Classification: Confidential", size=Pt(11), color=GRAY, align=WD_ALIGN_PARAGRAPH.CENTER)

doc.add_page_break()

# ===== TABLE OF CONTENTS =====
doc.add_heading("Table of Contents", level=1)
toc_items = [
    "1. Executive Summary",
    "2. What NemoClaw Is",
    "3. PowerSpec Hardware Specifications",
    "4. Agent Architecture (SDLC Components)",
    "5. Model Providers",
    "6. Skills Portability Matrix",
    "7. Cron Jobs Decision Matrix",
    "8. Port Allocation Map",
    "9. Debug Issues & Known Failures",
    "10. Implementation Phases & Status",
    "11. Eric's Outstanding Action Items",
    "12. Scope Decisions Log",
    "13. Risk Register",
    "14. Rollback Plan",
    "15. Next Steps Post-Prototype",
]
for item in toc_items:
    add_para(item, size=Pt(11), color=BLUE)

doc.add_page_break()

# ===== SECTION 1: Executive Summary =====
doc.add_heading("1. Executive Summary", level=1)
add_para(
    "NemoClaw (NVIDIA's security-sandboxed OpenClaw wrapper) prototype plan was fully designed, "
    "audited, and approved on April 12, 2026. Phases 2 and 3 are ready for Jarvis to execute "
    "automatically once Eric completes Phase 0 (WSL2 + GPU setup) and Phase 1 (NemoClaw install) "
    "on the PowerSpec PC."
)
add_bullet(" PowerSpec PC (Intel i9-14900KF, 128GB DDR5, RTX 5080 16GB)", "Hardware:")
add_bullet(" Deploy NemoClaw on WSL2 Ubuntu 22.04 alongside existing Docker services", "Target:")
add_bullet(" 18790 (Mac keeps 18789)", "Gateway port:")
add_bullet(" 19 portable skills, 11 crons, TUI-only (no Telegram on prototype)", "Scope:")
add_bullet(" Cohesity Google Drive (Eric.brown@cohesity.com) for NemoClaw outputs", "File storage:")
add_bullet(" 1.5–2.5 hours (Jarvis runs Phase 2+3 automatically)", "Estimated time to complete once Eric does Phase 0/1:")

# ===== SECTION 2: What NemoClaw Is =====
doc.add_heading("2. What NemoClaw Is", level=1)
add_para(
    "NemoClaw is a security/sandboxing wrapper around OpenClaw that adds:"
)
features = [
    "OpenShell runtime — kernel-level sandbox (Landlock + seccomp + netns)",
    "Nemotron models — NVIDIA's local inference models",
    "Privacy Router — routes inference traffic with credentials kept on host",
    "Policy-based security — egress control, filesystem isolation",
    "Guided onboarding wizard (single-command install)",
    "1M token context window vs OpenClaw's 200K",
    "SOC 2 compliance features",
    "5x throughput with Nemotron 3 Super",
    "Native enterprise integrations: Salesforce, ServiceNow, SAP",
]
for f in features:
    add_bullet(f)

add_para("")
p = doc.add_paragraph()
r = p.add_run("NemoClaw is NOT a replacement for Mac OpenClaw — it is an upgrade/evaluation layer. Both run in parallel.")
r.bold = True
r.font.size = Pt(10.5)
r.font.name = 'Calibri'

# ===== SECTION 3: PowerSpec Hardware Specifications =====
doc.add_heading("3. PowerSpec Hardware Specifications", level=1)
doc.add_heading("Hardware Compatibility", level=2)

hw_headers = ["Component", "Specification", "NemoClaw Requirement", "Status"]
hw_rows = [
    ["CPU", "Intel Core i9-14900KF, 24 cores / 32 threads", "4 vCPU minimum", "✅ Exceeds"],
    ["RAM", "128 GB DDR5", "8 GB minimum (16 GB rec.)", "✅ Exceeds"],
    ["GPU", "NVIDIA RTX 5080 16GB, CUDA 13.2, Driver 32.0.15.9597", "Optional (recommended)", "✅ Excellent"],
    ["Storage", "1608 GB free (Samsung NVMe 990)", "20 GB minimum", "✅ Exceeds"],
    ["Node.js", "v24.14.1", "v22.16+", "✅ Meets"],
    ["Docker", "Docker Desktop 29.3.1 (WSL2 backend)", "Docker 24.0+", "✅ Meets"],
    ["WSL2", "docker-desktop distro present", "Ubuntu 22.04 required", "⚠️ Needs Ubuntu-22.04"],
    ["OS", "Windows 11 Home 25H2", "Windows with WSL2", "✅ Meets"],
    ["Tailscale IP", "100.81.21.114", "—", "✅ Active"],
]
add_table(doc, hw_headers, hw_rows)

doc.add_heading("Currently Running Docker Services", level=2)
docker_headers = ["Service", "Port", "Memory", "Conflict Risk"]
docker_rows = [
    ["FinancialReportApp API", ":8001", "~512MB", "None"],
    ["FinancialReportApp Frontend", ":3001", "~256MB", "None"],
    ["FinancialReportApp Postgres", ":5433", "~256MB", "None"],
    ["FinancialReportApp Redis", ":6380", "~128MB", "None"],
    ["FinancialReportApp Celery", "—", "~256MB", "None"],
    ["ContractAnalyzer API", ":8000", "~512MB", "None"],
    ["ContractAnalyzer Postgres", ":5432", "~256MB", "None"],
    ["ContractAnalyzer Redis", ":6379", "~128MB", "None"],
    ["ContractAnalyzer MinIO", ":9000/:9001", "~256MB", "None"],
    ["ContractAnalyzer Celery", "—", "~256MB", "None"],
    ["Ollama", ":11434", "~4–8GB", "Shared with NemoClaw"],
]
add_table(doc, docker_headers, docker_rows)

add_para("")
p = doc.add_paragraph()
r = p.add_run("Total: ~7–11GB of 128GB used. NemoClaw has ample headroom.")
r.bold = True
r.font.size = Pt(10.5)
r.font.name = 'Calibri'

# ===== SECTION 4: Agent Architecture =====
doc.add_heading("4. Agent Architecture (SDLC Components)", level=1)
doc.add_heading("All 8 Agents — Fully Portable to NemoClaw", level=2)

agent_headers = ["Agent ID", "Name", "Primary Model", "Fallback Models", "Role", "NemoClaw Status"]
agent_rows = [
    ["main", "Jarvis", "claude-opus-4-6", "grok-4.20, claude-sonnet-4-6", "Orchestrator / Main assistant", "✅ Portable"],
    ["researcher", "Researcher", "claude-opus-4-6", "grok-4.20, claude-sonnet-4-6", "Research and web intelligence", "✅ Portable"],
    ["planner", "Planner", "claude-opus-4-6", "grok-4.20, claude-sonnet-4-6", "Plan authoring, Mermaid diagrams", "✅ Portable"],
    ["coder", "Coder", "claude-opus-4-6", "claude-sonnet-4-6", "Code implementation", "✅ Portable"],
    ["quality", "Quality", "grok-4.20", "claude-opus-4-6, claude-sonnet-4-6", "QA gate and output correctness", "✅ Portable"],
    ["monitor", "Monitor", "claude-sonnet-4-6", "grok-4.20", "System monitoring and health", "✅ Portable"],
    ["auditor", "External Auditor", "grok-4.20", "claude-sonnet-4-6", "Security, compliance, QA", "✅ Portable"],
    ["conductor", "Conductor", "claude-sonnet-4-6", "grok-4.20", "Task orchestration", "✅ Portable"],
]
add_table(doc, agent_headers, agent_rows)

doc.add_heading("Agent Configuration Defaults", level=2)
config_items = [
    ("Workspace:", " ~/.nemoclaw/sandbox/workspace"),
    ("Context pruning:", " cache-ttl, 1h"),
    ("Compaction:", " safeguard mode"),
    ("Timeout:", " 180s per agent"),
    ("Max concurrent:", " 6 agents"),
    ("Subagent limits:", " max 8 concurrent, depth 3, 5 children/agent"),
]
for prefix, val in config_items:
    add_bullet(val, prefix)

# ===== SECTION 5: Model Providers =====
doc.add_heading("5. Model Providers", level=1)

mp_headers = ["Provider", "Base URL", "Models", "Notes"]
mp_rows = [
    ["Anthropic", "Default", "claude-opus-4-6, claude-sonnet-4-6", "Primary — API key auth"],
    ["xAI", "api.x.ai/v1", "grok-4, grok-4.20", "Adversarial review, QA gate"],
    ["OpenAI", "Default", "gpt-5.1-codex", "Optional on prototype"],
    ["NVIDIA (NIM)", "integrate.api.nvidia.com", "Nemotron 3 Super", "NEW — requires nvapi key"],
    ["Ollama (local)", "localhost:11434/v1", "qwen3.5:35b-a3b, glm-4.7-flash", "Already running on PowerSpec — shared"],
]
add_table(doc, mp_headers, mp_rows)

add_para("")
p = doc.add_paragraph()
r = p.add_run("Note: ")
r.bold = True
r.font.size = Pt(10.5)
r2 = p.add_run("NemoClaw routes all inference through Privacy Router — API keys stay on host (outside sandbox).")
r2.font.size = Pt(10.5)

# ===== SECTION 6: Skills Portability Matrix =====
doc.add_heading("6. Skills Portability Matrix", level=1)

sk_headers = ["#", "Skill", "Category", "Portable?", "NemoClaw Action", "Notes"]
sk_rows = [
    ["1", "afrexai-contract-analyzer", "Analysis", "✅ Yes", "Copy as-is", "Pure analysis, no OS deps"],
    ["2", "ai-legal-assistant", "Analysis", "✅ Yes", "Copy as-is", "Pure analysis"],
    ["3", "auditor", "Pipeline", "✅ Yes", "Copy as-is", "Agent pipeline role"],
    ["4", "autoClaw", "Pipeline", "✅ Yes", "Copy as-is", "Self-evolving loop"],
    ["5", "blogwatcher", "Monitoring", "✅ Yes", "Copy as-is", "Web-based"],
    ["6", "cohesity-domain", "Knowledge", "✅ Yes", "Copy as-is", "Pure knowledge base"],
    ["7", "competitive-intel", "Research", "✅ Yes", "Copy as-is", "Web search-based"],
    ["8", "firecrawl", "Scraping", "✅ Yes", "Copy as-is", "Already targets PowerSpec"],
    ["9", "librarian", "Pipeline", "✅ Yes", "Copy as-is", "Knowledge manager"],
    ["10", "project-dynamo", "Analysis", "✅ Yes", "Copy as-is", "M&A analysis, pure knowledge"],
    ["11", "ragflow-search", "Search", "✅ Yes", "Copy as-is", "Already targets PowerSpec"],
    ["12", "railway-deployment", "DevOps", "✅ Yes", "Copy as-is", "Docker/Railway — portable"],
    ["13", "salesforce-analytics", "CRM", "✅ Yes", "Copy as-is", "API-based"],
    ["14", "slack-teams-hub", "Messaging", "✅ Yes", "Copy as-is", "API-based"],
    ["15", "snowflake-sql", "Data", "✅ Yes", "Copy as-is", "API-based"],
    ["16", "workday-analytics", "HR", "✅ Yes", "Copy as-is", "API-based"],
    ["17", "earnings-analyzer", "Finance", "⚠️ Partial", "Copy — disable email", "Analysis works; email needs gog"],
    ["18", "financial-report-gen", "Finance", "⚠️ Partial", "Copy — disable email", "Report gen works; email needs gog"],
    ["19", "remote-coder", "Compute", "⚠️ Partial", "Copy — rewrite paths", "Running ON PowerSpec; SSH-to-self pointless"],
    ["20", "monitor", "System", "⚠️ Partial", "Copy — update paths", "Mac-specific paths need Linux equivalents"],
    ["21", "mc-snapshot", "Dashboard", "⚠️ Partial", "Copy — update URL", "Change MC URL to 100.101.203.113:3000"],
    ["22", "tax-automation", "Finance", "⚠️ Partial", "Copy — defer Sheets", "Doc analysis works; Sheets deferred"],
    ["23", "gog", "Google", "⚠️ Partial", "Copy — non-functional", "Needs Google OAuth on WSL2 (deferred)"],
    ["24", "blucli", "Hardware", "❌ No", "Skip", "BluOS speakers — Mac LAN only"],
    ["25", "peekaboo", "macOS UI", "❌ No", "Skip", "macOS AppleScript/Accessibility only"],
    ["26", "tailscale-troubleshooting", "Network", "❌ No", "Skip", "Mac App Store Tailscale specific"],
    ["27", "google-oauth-reauth", "Auth", "❌ No", "Skip", "Mac-specific OAuth flow"],
    ["28", "linkedin-carousel", "Social", "❌ No", "Skip (scope)", "Not Cohesity business-relevant"],
]
add_table(doc, sk_headers, sk_rows)

add_para("")
p = doc.add_paragraph()
r = p.add_run("Summary: ")
r.bold = True
r.font.size = Pt(10.5)
r2 = p.add_run("16 copy as-is  |  7 partial (copy with caveats)  |  5 skip  |  Final migrate count: 19")
r2.font.size = Pt(10.5)

# ===== SECTION 7: Cron Jobs Decision Matrix =====
doc.add_heading("7. Cron Jobs Decision Matrix", level=1)

cron_headers = ["#", "Cron Job", "Agent", "Frequency", "Keep Mac", "PowerSpec", "Reason"]
cron_rows = [
    ["1", "Monitor Sweep", "monitor", "Every 3h", "✅", "❌", "Mac-specific paths"],
    ["2", "Cron Delivery Self-Heal", "main", "Every 30m", "✅", "❌", "Telegram-dependent"],
    ["3", "Auth Health Check", "monitor", "Every 4h", "✅", "❌", "Google OAuth - Mac only"],
    ["4", "Task Stall Respawner", "monitor", "Every 2h", "✅", "✅", "Portable"],
    ["5", "clawdbot-data-refresh", "main", "Daily midnight", "✅", "❌", "Low priority for prototype"],
    ["6", "Daily OpenClaw Doctor", "monitor", "5:00 AM", "✅", "✅", "Valuable health check"],
    ["7", "Daily Smoke Test", "monitor", "5:30 AM", "✅", "❌", "Mac-specific test suite"],
    ["8", "Daily OpenClaw Auto-Update", "main", "5:45 AM", "✅", "❌", "NemoClaw self-manages"],
    ["9", "Daily Tax Email Scan", "main", "5:45 AM", "✅", "❌", "Gmail-dependent"],
    ["10", "Daily Security Scan", "main", "5:50 AM", "✅", "❌", "Mac-specific tools"],
    ["11", "Stock Monitor", "monitor", "6:00 AM", "✅", "✅", "Web search based"],
    ["12", "Daily 6 AM AI Productivity", "main", "6:00 AM", "✅", "❌", "Email delivery required"],
    ["13", "Daily Subscription Monitor", "main", "6:10 AM", "✅", "❌", "Email-dependent"],
    ["14", "Weekly Competitor Analysis", "researcher", "Mon 7 AM", "✅", "✅", "Web research — portable"],
    ["15", "Weekly Claude Best Practices", "auditor", "Mon 7 AM", "✅", "❌", "Keep single source on Mac"],
    ["16", "Anthropic Ecosystem Daily", "monitor", "8:00 AM", "✅", "❌", "Single source on Mac"],
    ["17", "Daily Vibe Coding Security", "auditor", "8:00 AM", "✅", "❌", "Mac codebase audit"],
    ["18", "Weekly Background Infra", "main", "Mon 9 AM", "✅", "❌", "Infrastructure-dependent"],
]
add_table(doc, cron_headers, cron_rows)

add_para("")
p = doc.add_paragraph()
r = p.add_run("Summary: ")
r.bold = True
r2 = p.add_run("All 18 crons stay on Mac  |  4 also replicated on PowerSpec NemoClaw  |  0 moved exclusively to PowerSpec")
r2.font.size = Pt(10.5)

# ===== SECTION 8: Port Allocation Map =====
doc.add_heading("8. Port Allocation Map", level=1)

port_headers = ["Port", "Service", "Owner", "NemoClaw Impact"]
port_rows = [
    ["3001", "FinancialReportApp Frontend", "Docker", "No conflict"],
    ["5432", "ContractAnalyzer Postgres", "Docker", "No conflict"],
    ["5433", "FinancialReportApp Postgres", "Docker", "No conflict"],
    ["6379", "ContractAnalyzer Redis", "Docker", "No conflict"],
    ["6380", "FinancialReportApp Redis", "Docker", "No conflict"],
    ["8000", "ContractAnalyzer API", "Docker", "No conflict"],
    ["8001", "FinancialReportApp API", "Docker", "No conflict"],
    ["9000–9001", "MinIO (ContractAnalyzer)", "Docker", "No conflict"],
    ["11434", "Ollama", "Native Windows", "Shared — NemoClaw routes inference here"],
    ["18789", "RESERVED — Mac OpenClaw", "Mac (via Tailscale)", "⚠️ DO NOT USE"],
    ["18790", "NemoClaw Gateway", "NemoClaw", "✅ New allocation"],
]
add_table(doc, port_headers, port_rows)

# ===== SECTION 9: Debug Issues & Known Failures =====
doc.add_heading("9. Debug Issues & Known Failures Discovered During Build", level=1)

add_issue(1, "Mission Control Cross-Machine Access", "CRITICAL", "Found April 12, ~10:11 PDT",
    "Mission Control broken on both MacBook (shows OFFLINE/0 agents) AND PowerSpec (Chrome shows ERR_CONNECTION_REFUSED on localhost:3000/tasks)",
    "Next.js NEXT_PUBLIC_* env vars baked at build time as localhost:3001. Client-side fetches from PowerSpec hit PowerSpec's localhost (nothing runs there). Terminal page hardcoded http://127.0.0.1:18789.",
    "Added .env.local with NEXT_PUBLIC_BACKEND_URL=http://100.101.203.113:3001 and NEXT_PUBLIC_GATEWAY_URL=http://100.101.203.113:18789. Fixed terminal/page.tsx to use env var. Rebuilt + redeployed frontend. For PowerSpec users: Browser must go to http://100.101.203.113:3000 (Mac Tailscale IP), not localhost.",
    "✅ Fixed and deployed")

add_issue(2, "NemoClaw Default Port Conflict", "HIGH", "Discovered in Research Phase",
    "NemoClaw gateway defaults to port 18789 — same as Mac OpenClaw gateway. If both on Tailscale, causes silent conflict.",
    "NemoClaw onboard wizard default not configurable mid-wizard in some versions; port must be changed post-install via nemoclaw config set.",
    "Configure NemoClaw to port 18790 during onboard wizard OR run: nemoclaw config set gateway.port 18790 post-install.",
    "✅ Mitigated in plan (18790 allocated)")

add_issue(3, "Telegram Bot Token Single-Owner Constraint", "HIGH", "Discovered in Research Phase",
    "Only ONE OpenClaw instance can own the Telegram bot token at a time. Running NemoClaw with same token disconnects Mac Jarvis.",
    "Telegram bot API — a webhook or polling connection can only be registered once.",
    "NemoClaw prototype uses TUI/CLI only — no Telegram configuration. Mac retains sole ownership.",
    "✅ Resolved by design decision")

add_issue(4, "WSL2 NemoClaw Onboard Bug", "MEDIUM", "Known from Community",
    "nemoclaw onboard was reported broken on WSL2 at GTC launch (March 2026) — some users got cgroup v2 errors and GPU detection failures.",
    "NemoClaw's OpenShell sandbox uses Linux kernel features (Landlock, seccomp, cgroup v2) that require specific WSL2 configuration.",
    "(1) Enable systemd in /etc/wsl.conf before running installer. (2) Verify nvidia-smi works in WSL2 BEFORE running nemoclaw onboard. (3) Use NVIDIA's latest installer — fixes were issued post-GTC.",
    "⚠️ Risk mitigated in plan; will confirm during Phase 0 execution")

add_issue(5, "Google OAuth Cannot Run on WSL2", "MEDIUM", "Discovered in Research Phase",
    "gog CLI OAuth tokens are Mac-bound. Browser-based OAuth flow is complex inside WSL2 headless environment.",
    "OAuth requires browser redirect to localhost — WSL2's localhost forwarding adds complexity; Keychain not available on Linux.",
    "Google OAuth deferred for NemoClaw prototype. Skills requiring gog (gmail, calendar, sheets) are marked non-functional on NemoClaw until OAuth is set up post-prototype.",
    "✅ Deferred by design — not a blocker for prototype")

add_issue(6, "CIC Graph Search Performance", "LOW", "Found During CIC Build",
    "CIC entity graph (Cytoscape.js) showed layout thrash on each keystroke in search box — re-renders triggered graph re-layout.",
    "React state update on every keystroke triggered Cytoscape layout recalculation.",
    "Added useDeferredValue(search) in CICGraph.tsx to debounce search without blocking UI.",
    "✅ Fixed and committed")

add_issue(7, "CIC Graph Blank Canvas on API Error", "LOW", "Found During CIC Build",
    "If graph_data.json API call returned 404 or 500, the CIC canvas showed a blank white canvas with no user feedback.",
    "Missing error state handling in the fetch lifecycle.",
    "Added error state with red error message + Retry button; added if (!res.ok) throw new Error(...) before JSON parse.",
    "✅ Fixed and committed")

add_issue(8, "Docker Credential Manager Conflict on PowerSpec", "MEDIUM", "From PowerSpec Rebuild April 1",
    'Docker push/pull failed after PowerSpec rebuild — "error getting credentials from docker-credential-desktop".',
    "SSH sessions cannot access Windows Credential Manager (requires Windows GUI session). Docker Desktop sets credsStore=\"desktop\" by default.",
    'Renamed docker-credential-desktop.exe and docker-credential-wincred.exe helpers; set credsStore="" in ~/.docker/config.json.',
    "✅ Fixed (persists across reboots)")

add_issue(9, "Next.js NEXT_PUBLIC_ Env Vars Baked at Build Time", "Documented for Future", "",
    "Any change to NEXT_PUBLIC_BACKEND_URL or NEXT_PUBLIC_GATEWAY_URL requires a full frontend rebuild, not just a server restart.",
    "Next.js inlines NEXT_PUBLIC_ variables at build time (not runtime) for client-side code.",
    "For cross-machine deployments, use runtime config (e.g., server-side env vars or /api/config endpoint) instead of NEXT_PUBLIC_ for URLs that change by host.",
    "📝 Documented — future builds should use runtime config")

# ===== SECTION 10: Implementation Phases & Status =====
doc.add_heading("10. Implementation Phases & Status", level=1)

phase_headers = ["Phase", "Description", "Owner", "Duration", "Status"]
phase_rows = [
    ["Phase 0", "WSL2 Ubuntu 22.04 + NVIDIA GPU setup + NVIDIA API key", "Eric (manual)", "30–45 min", "🔴 PENDING"],
    ["Phase 1", "NemoClaw install + onboard wizard", "Eric (manual)", "20–30 min", "🔴 PENDING"],
    ["Phase 2", "Workspace migration + API config + network policy", "Jarvis (automated via SSH)", "45–90 min", "⏳ Ready to execute"],
    ["Phase 3", "17-item validation checklist + smoke test script", "Jarvis + Eric", "30–60 min", "⏳ Ready to execute"],
    ["Total", "", "", "2.5–4 hours", ""],
]
add_table(doc, phase_headers, phase_rows)

# ===== SECTION 11: Eric's Outstanding Action Items =====
p = doc.add_heading("11. Eric's Outstanding Action Items", level=1)
# Override heading color to red/orange
for run in p.runs:
    run.font.color.rgb = RED_ORANGE

action_items = [
    ("1. PHASE 0 — Install WSL2 Ubuntu 22.04 on PowerSpec",
     "Command: wsl --install -d Ubuntu-22.04 (run in PowerShell as Administrator)\nThen: Enable systemd in /etc/wsl.conf, configure Docker Desktop WSL integration, install NVIDIA container toolkit"),
    ("2. PHASE 0 — Verify GPU Access in WSL2",
     "Command: nvidia-smi (must show RTX 5080 before proceeding)"),
    ("3. PHASE 0 — Get NVIDIA API Key",
     "URL: https://build.nvidia.com → sign in → Get API Key\nSave the nvapi-... key — needed during NemoClaw onboard wizard"),
    ("4. PHASE 1 — Run NemoClaw Installer",
     "Command (in WSL2 Ubuntu): curl -fsSL https://nvidia.com/nemoclaw.sh | bash\nSettings: Port = 18790, Provider = Anthropic, Telegram = Skip"),
    ("5. GOOGLE DRIVE DECISION — Confirm file storage approach",
     "Option A: Kathir Nagireddy (IT) provisions a Cohesity G Drive service account for NemoClaw\nOption B: Eric does OAuth himself with Eric.brown@cohesity.com"),
]

for title, detail in action_items:
    p = doc.add_paragraph()
    r = p.add_run(title)
    r.bold = True
    r.font.size = Pt(12)
    r.font.color.rgb = RED_ORANGE
    r.font.name = 'Calibri'
    
    for line in detail.split('\n'):
        dp = doc.add_paragraph(style='List Bullet')
        dr = dp.add_run(line)
        dr.font.size = Pt(10.5)
        dr.font.name = 'Calibri'

add_para("")
p = doc.add_paragraph()
r = p.add_run("Once items 1–4 are done, Jarvis takes over automatically (Phase 2 + Phase 3).")
r.bold = True
r.font.size = Pt(11)
r.font.color.rgb = GREEN

# ===== SECTION 12: Scope Decisions Log =====
doc.add_heading("12. Scope Decisions Log", level=1)
add_para("Final scope decisions made on April 12, 2026:")

scope_decisions = [
    ("Telegram:", " Mac retains sole ownership. NemoClaw prototype = TUI/CLI only."),
    ("File Storage:", " Cohesity Google Drive (Eric.brown@cohesity.com) for all NemoClaw file output. Mac Jarvis personal Dropbox stays as-is."),
    ("Skills Removed:", " linkedin-carousel (not Cohesity business-relevant), blucli, peekaboo, tailscale-troubleshooting, gog/google-oauth-reauth (Google OAuth deferred)"),
    ("Skills Kept:", " financial-report-gen ✅, earnings-analyzer ✅ (report generation works even without email delivery)"),
    ("Crons Removed from NemoClaw:", " Daily 6 AM Briefing, Daily Tax Email Scan, Daily Subscription Monitor, Weekly Background Info Update, clawdbot-data-refresh, Auth Health Check"),
    ("NemoClaw Config Rule:", " NemoClaw implementation MUST NOT change any Mac OpenClaw config files"),
    ("Final skill count:", " 19 migrate | 9 skipped"),
    ("Final cron count on NemoClaw:", " 11 active (4 replicated from Mac + 7 NemoClaw-specific)"),
]
for prefix, val in scope_decisions:
    add_bullet(val, prefix)

# ===== SECTION 13: Risk Register =====
doc.add_heading("13. Risk Register", level=1)

risk_headers = ["#", "Risk", "Likelihood", "Impact", "Mitigation"]
risk_rows = [
    ["1", "nemoclaw onboard fails on WSL2", "Medium", "High", "Verify nvidia-smi first; check NVIDIA GitHub for latest fixes"],
    ["2", "GPU not detected in WSL2", "Low", "High", "Verify nvidia-smi BEFORE running installer; restart WSL if needed"],
    ["3", "Docker resource contention", "Low", "Medium", ".wslconfig caps WSL2 at 64GB; monitor with docker stats"],
    ["4", "NemoClaw uses port 18789 despite config", "Low", "Medium", "Verify with ss -tlnp after install; reconfigure if needed"],
    ["5", "Sandbox blocks needed API egress", "High", "Low", "Start permissive; add allowlist entries as errors surface"],
    ["6", "Workspace import path wrong", "Medium", "Low", "nemoclaw config show reveals actual sandbox root"],
    ["7", "Ollama not reachable from WSL2", "Low", "Medium", "Verify localhostForwarding=true in .wslconfig; test with curl"],
    ["8", "NemoClaw alpha software instability", "Medium", "Medium", "Prototype only — Mac Jarvis remains primary; no production dependency"],
]
add_table(doc, risk_headers, risk_rows)

# ===== SECTION 14: Rollback Plan =====
doc.add_heading("14. Rollback Plan", level=1)
p = doc.add_paragraph()
r = p.add_run("NemoClaw is fully reversible — Mac OpenClaw is completely unaffected throughout.")
r.bold = True
r.font.size = Pt(11)

doc.add_heading("What NemoClaw Changes (all reversible):", level=2)
reversible = [
    "Ubuntu-22.04 WSL2 distro: wsl --unregister Ubuntu-22.04",
    "NVIDIA container toolkit: removed with distro unregister",
    "NemoClaw files: removed with distro unregister",
    "Docker Desktop WSL integration: toggle off in Docker Desktop settings",
    r".wslconfig memory limit: delete C:\Users\Eric Brown\.wslconfig",
    "Port 18790: freed when NemoClaw stops",
]
for item in reversible:
    add_bullet(item)

doc.add_heading("What is NOT affected by rollback:", level=2)
unaffected = [
    "Mac OpenClaw (completely independent)",
    "Existing Docker containers (run in docker-desktop distro, not Ubuntu-22.04)",
    "Ollama (runs on Windows native)",
    "Windows itself",
    "Tailscale",
]
for item in unaffected:
    add_bullet(item)

# ===== SECTION 15: Next Steps Post-Prototype =====
doc.add_heading("15. Next Steps Post-Prototype", level=1)

next_steps = [
    ("1. Google OAuth on WSL2", " — set up gog CLI with browser-based OAuth; enables Gmail/Calendar/Sheets skills"),
    ("2. Telegram", " — create second bot or webhook routing when NemoClaw promoted to production"),
    ("3. Cron migration", " — move remaining crons when PowerSpec becomes primary compute host"),
    ("4. Ajax server planning", " — use NemoClaw prototype learnings to design full Ajax deployment (96-core AMD Threadripper PRO, 1TB RAM, 2× RTX PRO 5000 48GB)"),
    ("5. Local NIM inference", " — test Nemotron models locally on RTX 5080 (16GB VRAM)"),
    ("6. Dual-instance orchestration", " — Mac Jarvis dispatching GPU workloads to PowerSpec NemoClaw"),
]
for prefix, val in next_steps:
    add_bullet(val, prefix)

# ===== SAVE =====
output_path = os.path.expanduser("~/Documents/NemoClaw_PowerSpec_Project_Report_2026-04-13.docx")
doc.save(output_path)
size = os.path.getsize(output_path)
print(f"DONE: File saved to ~/Documents/NemoClaw_PowerSpec_Project_Report_2026-04-13.docx")
print(f"File size: {size:,} bytes ({size/1024:.1f} KB)")
